# Generated by Django 4.0.3 on 2022-04-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_streak', models.IntegerField()),
                ('unlimited_streak', models.IntegerField()),
                ('timed_streak', models.IntegerField()),
                ('blitz_streak', models.IntegerField()),
                ('daily_streak_max', models.IntegerField()),
                ('unlimited_streak_max', models.IntegerField()),
                ('timed_streak_max', models.IntegerField()),
                ('blitz_streak_max', models.IntegerField()),
                ('user_bio', models.TextField(max_length=1000)),
            ],
        ),
    ]
