# Generated by Django 4.0.3 on 2022-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.TextField(default='user_name'),
            preserve_default=False,
        ),
    ]
