# Generated by Django 3.2.12 on 2022-05-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='win',
            new_name='success',
        ),
    ]
