# Generated by Django 3.2.12 on 2022-05-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('num_of_letters', models.IntegerField()),
                ('word_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Word',
            },
        ),
    ]
