# Generated by Django 3.2.12 on 2022-03-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='text',
            new_name='word',
        ),
    ]
