# Generated by Django 4.0.3 on 2022-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timed',
            name='attempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timed',
            name='word_length',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='timed',
            table='timed_stats',
        ),
    ]
